# Generated by Django 4.0.4 on 2022-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_alter_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='tour/%Y/%m'),
        ),
    ]
